spring.application.name=project-manager
spring.datasource.url=jdbc:h2:mem:project_db;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.show-sql=true

jwt.secret=my-super-secret-key-that-is-at-least-32-characters-long-for-hs256!

# Mail Properties
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=dummy
spring.mail.password=dummy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
